your_user = 'mrgvd_wp8'
your_host = 'mrgvd.beget.tech'
your_password = '28yC&Cp%'
your_database = 'mrgvd_wp8'
# your_schema = 'authorization_bot'
your_port = '3306'
TELEGRAM_TOKEN = '6099510947:AAGMcj5qbhcmv7CKw6eDAbbHExtY4NXurtA'